plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "tmp/**/*"

Layout/LineLength:
  Max: 130

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 25

Style/Documentation:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

RSpec:
  Enabled: true

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 3

RSpec/DescribeClass:
  Enabled: true

RSpec/NamedSubject:
  Enabled: false
